# Generated by Django 5.2.8 on 2026-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Inquiry Received'), ('Quoted', 'Price Offered'), ('Accepted', 'Accepted by Buyer'), ('Declined', 'Declined'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Modern', 'Modern'), ('Decoration', 'Decoration'), ('Office', 'Office'), ('Hotel', 'Hotel')], default='Green', max_length=50),
        ),
    ]
