# Generated by Django 5.2.8 on 2026-02-26 07:12

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_asortieknowledge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asortieknowledge',
            name='knowledge_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asortieknowledge',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
